### ISSUE TITLE
Running Kiva on Tomcat

### ISSUE THREAD

**Issue by felipevb** [unchartedsoftware/influent#4]
After building influent successfully, I go to the kiva directory and run "mvn package tomcat:run" in the command prompt. I get the following java exception

```
SEVERE: Exception starting filter guiceFilter
java.lang.ClassCastException: com.google.inject.servlet.GuiceFilter cannot be cast to javax.servlet.Filter
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:275)
	at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(ApplicationFilterConfig.java:422)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:115)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4001)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4651)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
	at org.apache.catalina.startup.Embedded.start(Embedded.java:825)
	at org.codehaus.mojo.tomcat.AbstractRunMojo.startContainer(AbstractRunMojo.java:558)
	at org.codehaus.mojo.tomcat.AbstractRunMojo.execute(AbstractRunMojo.java:255)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

It appears tomcat is running but I get a blank page when i go to localhost:8080

**Comment by jamespr** [comment]
Hello,

I'm getting the same error. For now, try:
```
mvn package jetty:run
```

I'll look into the tomcat configuration in the meantime.

Thanks,
James Robinson
Senior Visualization Developer | Uncharted™
formerly Oculus Info Inc.

**Comment by felipevb** [comment]
Hello James,

I tried that and I still get java exceptions. This time they are different. It appears to be a bad config of the JVM memory size. Not sure where to look for this. As for my system memory, I still have a few gigs free (~3.6GB), so I assume that is not the issue.

```
INFO: An exception was caught and reported. Message: net.sf.ehcache.config.InvalidConfigurationException: There is one error in your configuration: 
        * CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly


net.sf.ehcache.config.InvalidConfigurationException: There is one error in your configuration: 
        * CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly


        at net.sf.ehcache.config.CacheConfiguration.setupFor(CacheConfiguration.java:1591)
        at net.sf.ehcache.CacheManager.initializeEhcache(CacheManager.java:1285)
        at net.sf.ehcache.CacheManager.addCacheNoCheck(CacheManager.java:1337)
        at net.sf.ehcache.CacheManager.addConfiguredCaches(CacheManager.java:758)
        at net.sf.ehcache.CacheManager.doInit(CacheManager.java:459)
        at net.sf.ehcache.CacheManager.init(CacheManager.java:377)
        at net.sf.ehcache.CacheManager.<init>(CacheManager.java:259)
        at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1037)
        at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:983)
        at net.sf.ehcache.CacheManager.create(CacheManager.java:959)
        at oculus.aperture.rest.RestModule.configureServlets(RestModule.java:245)
        at com.google.inject.servlet.ServletModule.configure(ServletModule.java:53)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at oculus.aperture.ApertureServerConfig.getInjector(ApertureServerConfig.java:165)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
        at oculus.aperture.ApertureServerConfig.contextInitialized(ApertureServerConfig.java:137)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:634)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:228)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1132)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:577)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:491)
        at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:160)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.eclipse.jetty.server.handler.HandlerCollection$1.run(HandlerCollection.java:200)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
        at java.lang.Thread.run(Thread.java:745)

2015-03-19 21:46:47.953:WARN::Failed startup of context JettyWebAppContext@38db525e@38db525e/kiva,[file:/home/vagrant/influent/kiva/target/tmp/webinf/, [file:/home/vagrant/influent/influent-client/influent-clientjs/src/, file:/home/vagrant/influent/kiva/src/main/webapp/, file:/home/vagrant/influent/kiva/target/kiva-1.3.6/]],[file:/home/vagrant/influent/influent-client/influent-clientjs/src/, file:/home/vagrant/influent/kiva/src/main/webapp/, file:/home/vagrant/influent/kiva/target/kiva-1.3.6/]
com.google.inject.CreationException: Guice creation errors:||1) An exception was caught and reported. Message: There is one error in your configuration: |?* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly|||  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)||1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at oculus.aperture.ApertureServerConfig.getInjector(ApertureServerConfig.java:165)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
        at oculus.aperture.ApertureServerConfig.contextInitialized(ApertureServerConfig.java:137)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:634)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:228)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1132)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:577)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:491)
        at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:160)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.eclipse.jetty.server.handler.HandlerCollection$1.run(HandlerCollection.java:200)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
        at java.lang.Thread.run(Thread.java:745)
Caused by: 
net.sf.ehcache.config.InvalidConfigurationException: There is one error in your configuration: |?* CacheManager configuration: You've assigned more memory to the on-heap than the VM can sustain, please adjust your -Xmx setting accordingly||
        at net.sf.ehcache.config.CacheConfiguration.setupFor(CacheConfiguration.java:1591)
        at net.sf.ehcache.CacheManager.initializeEhcache(CacheManager.java:1285)
        at net.sf.ehcache.CacheManager.addCacheNoCheck(CacheManager.java:1337)
        at net.sf.ehcache.CacheManager.addConfiguredCaches(CacheManager.java:758)
        at net.sf.ehcache.CacheManager.doInit(CacheManager.java:459)
        at net.sf.ehcache.CacheManager.init(CacheManager.java:377)
        at net.sf.ehcache.CacheManager.<init>(CacheManager.java:259)
        at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:1037)
        at net.sf.ehcache.CacheManager.newInstance(CacheManager.java:983)
        at net.sf.ehcache.CacheManager.create(CacheManager.java:959)
        at oculus.aperture.rest.RestModule.configureServlets(RestModule.java:245)
        at com.google.inject.servlet.ServletModule.configure(ServletModule.java:53)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at oculus.aperture.ApertureServerConfig.getInjector(ApertureServerConfig.java:165)
        at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
        at oculus.aperture.ApertureServerConfig.contextInitialized(ApertureServerConfig.java:137)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:634)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:228)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1132)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:577)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:491)
        at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:160)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
        at org.eclipse.jetty.server.handler.HandlerCollection$1.run(HandlerCollection.java:200)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
        at java.lang.Thread.run(Thread.java:745)
2015-03-19 21:46:47.976:INFO::Started SelectChannelConnector@0.0.0.0:8080
[INFO] Started Jetty Server
```

**Comment by jamespr** [comment]
This setting can be changed in kiva\src\main\resources\ehcache.xml, you may need to reduce the amount of heap assigned to the dynamicClusteringCache.

It looks like Jetty has started too. So you should find Kiva is reachable at localhost:8080/kiva

**Comment by felipevb** [comment]
That did the trick. Just increased the RAM size to 8Gb in my VM seeing how the ehcache.xml is set to that.

**Comment by jamespr** [comment]
Also, depending on what you're doing with Influent - you might want to check out Influent 2.0. Contact us through http://influent.org/ for more details.
