### ISSUE TITLE
Unable to fetch data from Solr "Error paging search results null"

### ISSUE THREAD

**Issue by Priyankadas16** [unchartedsoftware/influent#8]
Hi Team,

Currently i am getting "oculus.aperture.common.rest.ApertureServerResource - Exception or error caught in ApertureServerResource" Exception in "SolrBaseSearchIterator.java" class of influent server where its not able to get the result from solar query, hence throwing "Error paging search results null" AvroRunitimeException Mesg. Below is the full Error log, Request you to please help on this

oculus.aperture.common.rest.ApertureServerResource - Exception or error caught in ApertureServerResource
org.apache.avro.AvroRuntimeException: Error paging search results null
	at influent.server.search.SolrBaseSearchIterator.doRefresh(SolrBaseSearchIterator.java:238)
	at influent.server.search.SolrBaseSearchIterator.hasNext(SolrBaseSearchIterator.java:124)
	at influent.server.search.SolrEntitySearch.search(SolrEntitySearch.java:138)
	at influent.kiva.server.search.KivaEntitySearch.search(KivaEntitySearch.java:116)
	at influent.server.search.SolrEntitySearch.search(SolrEntitySearch.java:84)
	at influent.server.rest.EntitySearchResource.search(EntitySearchResource.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:503)
	at org.restlet.resource.ServerResource.post(ServerResource.java:1216)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:592)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:649)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:952)
	at org.restlet.resource.Finder.handle(Finder.java:246)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:431)
	at org.restlet.routing.Router.handle(Router.java:648)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
	at org.restlet.Application.handle(Application.java:381)
	at org.restlet.ext.servlet.ServletAdapter.service(ServletAdapter.java:206)
	at oculus.aperture.rest.RestletServlet.service(RestletServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at oculus.aperture.rest.RestModule$CustomPageCachingFilter.doFilter(RestModule.java:159)
	at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:86)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:514)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:920)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:856)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:247)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:151)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1066)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:510)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:450)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at influent.kiva.server.search.KivaEntitySearchIterator.buildResultFromDocument(KivaEntitySearchIterator.java:127)
	at influent.kiva.server.search.KivaEntitySearchIterator.buildResultFromDocument(KivaEntitySearchIterator.java:55)
	at influent.server.search.SolrBaseSearchIterator.doRefresh(SolrBaseSearchIterator.java:225)
	... 69 more

Regards

Priyanka

**Comment by dgauldie** [comment]
Have you set up a Apache Solr instance yet? If not please follow the instructions located here:
http://community.influent.org/community/developer-docs/how-to/search-config/#solr

**Comment by Priyankadas16** [comment]
Hi ,

I am following the same steps.
I am able to connect Solr and hit the query, but its giving exception at

String uid =
sd.getFieldValue(DataPropertyDescriptorHelper.mapKey(FL_RequiredPropertyKey.
ID.name(), entityDescriptors.getProperties(), type)).toString();


line in KIvaEntitySearchIterator.java, If i do Sysout entityDescriptors
just above this line its printing the information , but at this place it
gives null pointer exception


Regards

priyanka

**Comment by Priyankadas16** [comment]
Hi Team,

I am still getting "Error paging search results null" Exception.

When i am printing SolrDocument in SolrBaseSearchIterator.java i am getting
Solr result over there like

{lenders_inviteeCount=1, lon=-95.0, lenders_loanBecause=[If we all help
each other, we'll all be better off.], text=[If we all help each other,
we'll all be better off.], lenders_countryCode=CA, lenders_personalUrl=,
lenders_memberSince=Sun Jul 27 20:48:39 IST 2008,
lenders_occupation=engineer & students, lenders_loanCount=1444,
lenders_name=[Danielle Katz], lat=60.0, lenders_occupationalInfo=[],
id=lphilip9639, lenders_inviterId=0, image_id=683265, timestamp=Tue Jun 24
21:42:20 IST 2014, score=0.7499079}


but it won't provide any output for score or result, and finally getting
null Exception.


Any Suggestion?


Thanks in advance


Priyanka

**Comment by jamespr** [comment]
Hi Priyanka,

In order to more effectively diagnose the issue, can you provide more detail on the steps for us to reproduce the same problem? i.e.:

- What steps did you follow to get to where you are now?
- What servers are you connecting to? What type/version of database?
- Have you made any modifications to Influent?
- Are you running one of Influent's example applications (unmodified), or are you creating a new one?

The example apps will work 'out-of-the-box', connecting to the example servers. Have you run any of the example applications yet?

Thanks,
James

**Comment by Priyankadas16** [comment]
Hi James,

I am trying to run Kiva example on my local system, i am doing any
modification into it. I am using kiva sample data provided by your team.

I have followed configuration document steps to build influent.
I am using mysql database  Ver 14.14 Distrib 5.6.22, for osx10.9

I have made following changes in kiva server.config

influent.midtier.database.type = mysql

influent.midtier.database.url = jdbc:mysql://localhost:3306/kiva

influent.midtier.database.driver = com.mysql.jdbc.Driver

influent.midtier.user.name = root

influent.midtier.user.password =root

influent.midtier.solr.url = http://localhost:8983/solr/demoKivaSolr


Attached is my config file with the changes i have made.


Apart from this i have not made any changes.


Regards

Priyanka

**Comment by jamespr** [comment]
Hi Priyanka,

I suspect this issue is happening because you're using Influent 1.3.6 example data with Influent 2.0.0-beta. A new 2.0.0 local standalone demo should be available next week.

In the meantime:

- Our Kiva example servers (i.e. Kiva sample app default configuration for release 2.0.0) is configured for use with version 2.0.0:

```
# Database Server Properties`
#--------------------------
influent.midtier.server.name = influent.uncharted.software`
influent.midtier.server.port = 1433`
influent.midtier.database.name = Kiva
influent.midtier.user.name = influent
influent.midtier.user.password = 9E~1rVb' 0E=sicfo

#-----------------------
# Solr Server Properties
#-----------------------
influent.midtier.solr.entities.url = http://solr.uncharted.software:8983/solr/kiva-entities
influent.midtier.solr.links.url = http://solr.uncharted.software:8983/solr/kiva-links

#------------------------
# Pattern Search Database
#------------------------
influent.pattern.search.remoteURL = http://solr.uncharted.software:8805/pattern/search/example
influent.pattern.search.useHMM = false
```
- You may also wish to try our 2.0.0-beta demo at http://community.influent.org/kiva2/

James

**Comment by Priyankadas16** [comment]
Thankyou James.

-----Original Message-----
